In [7]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [8]:
from utils import *

In [104]:
import glob
import os
import pandas as pd
from tqdm.notebook import tqdm
import matplotlib.pyplot as plt
import os
import numpy as np

In [10]:
paths = sorted(glob.glob(os.path.join(RAW_DATA_PATH, '*.csv')))
print(os.getcwd())
print(os.listdir())

/Users/ishahameed/Documents/Classes/Third_Year/498/analyses/NVFEL498/Notebooks
['ExtractingTripInfo.ipynb', 'midas-applied-ds', '.DS_Store', 'TripFuelConsumption.ipynb', '__pycache__', 'CompilingData.ipynb', 'VED', 'utils.py', '.ipynb_checkpoints']

In [35]:
print(RAW_DATA_PATH)
nonEVpath = 'VED_Static_Data_ICE&HEV.csv'

midas-applied-ds/Data/Raw/VED/

In [170]:
paths[:5]
print(paths[0])

midas-applied-ds/Data/Raw/VED/VED_171101_week.csv

In [38]:
os.path.basename(paths[10])
os.path.basename(paths[0])

'VED_171101_week.csv'

In [39]:
data = pd.read_csv(paths[0])

In [60]:
nonEV_data = pd.read_csv(nonEVpath)
nonEV_data

,VehId,Vehicle Type,Vehicle Class,Engine Configuration & Displacement,Transmission,Drive Wheels,Generalized_Weight
0,2,ICE,Car,4-FI 2.0L T/C,NO DATA,NO DATA,3500
1,5,HEV,Car,4-GAS/ELECTRIC 2.0L,NO DATA,NO DATA,3500
2,7,ICE,SUV,6-FI 3.6L,AUTOMATIC,NO DATA,4500
3,8,ICE,Car,4-FI 1.5L,5-SP MANUAL,NO DATA,2500
4,12,ICE,Car,4-FI 1.8L,NO DATA,NO DATA,2500
...,...,...,...,...,...,...,...
351,616,ICE,NO DATA,V6 3.5L,5-SP Automatic,NO DATA,NO DATA
352,618,ICE,NO DATA,V6 3.5L,4-SP Automatic,NO DATA,NO DATA
353,624,ICE,NO DATA,H-4 2.5L,5-SP Automatic,NO DATA,NO DATA
354,625,ICE,NO DATA,I-4 1.8L,CVT,NO DATA,3000
355,630,ICE,NO DATA,I-4 2.4L,Automatic,NO DATA,NO DATA

In [122]:
nonEV_trips = data['VehId'].isin(nonEV_data['VehId'])
nonEV_trips = data[nonEV_trips]

nonEV_tripNum = nonEV_trips.Trip.unique()
nonEV_trips
#nonEV_tripNum

,DayNum,VehId,Trip,Timestamp(ms),Latitude[deg],Longitude[deg],Vehicle Speed[km/h],MAF[g/sec],Engine RPM[RPM],Absolute Load[%],...,Air Conditioning Power[kW],Air Conditioning Power[Watts],Heater Power[Watts],HV Battery Current[A],HV Battery SOC[%],HV Battery Voltage[V],Short Term Fuel Trim Bank 1[%],Short Term Fuel Trim Bank 2[%],Long Term Fuel Trim Bank 1[%],Long Term Fuel Trim Bank 2[%]
0,1.586651,8,706,0,42.277558,-83.698750,40.0,22.129999,2285.0,49.019608,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1.586651,8,706,200,42.277558,-83.698750,40.0,22.129999,2285.0,67.450981,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1.586651,8,706,1100,42.277558,-83.698750,45.0,22.129999,2285.0,67.450981,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1.586651,8,706,2100,42.277558,-83.698750,47.0,6.150000,2744.0,67.450981,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1.586651,8,706,4200,42.277558,-83.698750,48.0,21.440001,1982.0,67.450981,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
489409,7.992231,601,128,896900,42.288847,-83.753957,12.0,24.150000,2042.0,18.431374,...,NaN,NaN,NaN,NaN,NaN,NaN,28.125,NaN,7.03125,NaN
489410,7.992231,601,128,897100,42.288847,-83.753957,18.0,24.150000,2042.0,18.431374,...,NaN,NaN,NaN,NaN,NaN,NaN,28.125,NaN,7.03125,NaN
489411,7.992231,601,128,897900,42.288847,-83.753957,18.0,30.350000,2152.0,18.431374,...,NaN,NaN,NaN,NaN,NaN,NaN,28.125,NaN,7.03125,NaN
489412,7.992231,601,128,898100,42.288847,-83.753957,24.0,30.350000,2152.0,18.431374,...,NaN,NaN,NaN,NaN,NaN,NaN,28.125,NaN,7.03125,NaN
489413,7.992231,601,128,899500,42.288847,-83.753957,29.0,30.350000,2152.0,18.431374,...,NaN,NaN,NaN,NaN,NaN,NaN,28.125,NaN,7.03125,NaN

In [123]:
trip_706 = nonEV_trips.loc[nonEV_trips['Trip'] == 706]
nonEV_trips
trip_706

,DayNum,VehId,Trip,Timestamp(ms),Latitude[deg],Longitude[deg],Vehicle Speed[km/h],MAF[g/sec],Engine RPM[RPM],Absolute Load[%],...,Air Conditioning Power[kW],Air Conditioning Power[Watts],Heater Power[Watts],HV Battery Current[A],HV Battery SOC[%],HV Battery Voltage[V],Short Term Fuel Trim Bank 1[%],Short Term Fuel Trim Bank 2[%],Long Term Fuel Trim Bank 1[%],Long Term Fuel Trim Bank 2[%]
0,1.586651,8,706,0,42.277558,-83.698750,40.0,22.129999,2285.0,49.019608,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1.586651,8,706,200,42.277558,-83.698750,40.0,22.129999,2285.0,67.450981,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1.586651,8,706,1100,42.277558,-83.698750,45.0,22.129999,2285.0,67.450981,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1.586651,8,706,2100,42.277558,-83.698750,47.0,6.150000,2744.0,67.450981,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1.586651,8,706,4200,42.277558,-83.698750,48.0,21.440001,1982.0,67.450981,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
411326,6.698395,464,706,98900,42.263085,-83.780254,61.0,5.150000,1856.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
411327,6.698395,464,706,100300,42.263085,-83.780254,61.0,5.150000,1856.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
411328,6.698395,464,706,101000,42.263085,-83.780254,61.0,5.120000,1832.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
411329,6.698395,464,706,101600,42.263085,-83.780254,60.0,5.120000,1832.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
411330,6.698395,464,706,102600,42.263085,-83.780254,59.0,5.120000,1832.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [136]:
def haversine_distance(lat1, lon1, lat2, lon2):
   r = 6371
   phi1 = np.radians(lat1)
   phi2 = np.radians(lat2)
   delta_phi = np.radians(lat2 - lat1)
   delta_lambda = np.radians(lon2 - lon1)
   a = np.sin(delta_phi / 2)**2 + np.cos(phi1) * np.cos(phi2) *   np.sin(delta_lambda / 2)**2
   res = r * (2 * np.arctan2(np.sqrt(a), np.sqrt(1 - a)))
   return np.round(res, 2)

In [152]:
trip_706['MAF[g/sec]'].isna().value_counts()
#trip_706['Price'] = [x if x != 'NaN' else 0 for x in trip_706['MAF[g/sec]']]
trip_706.loc[trip_706['MAF[g/sec]'] != 'NaN', 'Fuel Flow'] = trip_706['MAF[g/sec]']*3600/(14.7*820)
trip_706['Inst Fuel Rate'] = trip_706['Fuel Flow']/trip_706['Vehicle Speed[km/h]']
trip_706
#trip_706['Inst Fuel Consumption']

/usr/local/anaconda3/envs/nvfel/lib/python3.7/site-packages/pandas/core/indexing.py:1676: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(ilocs[0], value, pi)
/usr/local/anaconda3/envs/nvfel/lib/python3.7/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.

,DayNum,VehId,Trip,Timestamp(ms),Latitude[deg],Longitude[deg],Vehicle Speed[km/h],MAF[g/sec],Engine RPM[RPM],Absolute Load[%],...,Short Term Fuel Trim Bank 1[%],Short Term Fuel Trim Bank 2[%],Long Term Fuel Trim Bank 1[%],Long Term Fuel Trim Bank 2[%],Fuel Flow,Inst Fuel Consumption,final_lat,final_lon,dist,Inst Fuel Rate
0,1.586651,8,706,0,42.277558,-83.698750,40.0,22.129999,2285.0,49.019608,...,NaN,NaN,NaN,NaN,6.609258,NaN,NaN,NaN,NaN,0.165231
1,1.586651,8,706,200,42.277558,-83.698750,40.0,22.129999,2285.0,67.450981,...,NaN,NaN,NaN,NaN,6.609258,0.00000,42.277558,-83.698750,0.00,0.165231
2,1.586651,8,706,1100,42.277558,-83.698750,45.0,22.129999,2285.0,67.450981,...,NaN,NaN,NaN,NaN,6.609258,0.00000,42.277558,-83.698750,0.00,0.146872
3,1.586651,8,706,2100,42.277558,-83.698750,47.0,6.150000,2744.0,67.450981,...,NaN,NaN,NaN,NaN,1.836735,0.00000,42.277558,-83.698750,0.00,0.039079
4,1.586651,8,706,4200,42.277558,-83.698750,48.0,21.440001,1982.0,67.450981,...,NaN,NaN,NaN,NaN,6.403186,0.00000,42.277558,-83.698750,0.00,0.133400
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
411326,6.698395,464,706,98900,42.263085,-83.780254,61.0,5.150000,1856.0,NaN,...,NaN,NaN,NaN,NaN,1.538079,2034.49987,42.264161,-83.780114,0.12,0.025214
411327,6.698395,464,706,100300,42.263085,-83.780254,61.0,5.150000,1856.0,NaN,...,NaN,NaN,NaN,NaN,1.538079,0.00000,42.263085,-83.780254,0.00,0.025214
411328,6.698395,464,706,101000,42.263085,-83.780254,61.0,5.120000,1832.0,NaN,...,NaN,NaN,NaN,NaN,1.529119,0.00000,42.263085,-83.780254,0.00,0.025068
411329,6.698395,464,706,101600,42.263085,-83.780254,60.0,5.120000,1832.0,NaN,...,NaN,NaN,NaN,NaN,1.529119,0.00000,42.263085,-83.780254,0.00,0.025485
411330,6.698395,464,706,102600,42.263085,-83.780254,59.0,5.120000,1832.0,NaN,...,NaN,NaN,NaN,NaN,1.529119,0.00000,42.263085,-83.780254,0.00,0.025917

In [169]:

trip_706['final_lat'] = trip_706['Latitude[deg]'].shift(1)
trip_706['final_lon'] = trip_706['Longitude[deg]'].shift(1)
trip_706['dist'] = haversine_distance(trip_706['Latitude[deg]'], trip_706['Longitude[deg]'], 
                                     trip_706['final_lat'], trip_706['final_lon'])

trip_706['Inst Fuel Consumption'] = trip_706['Inst Fuel Rate']*trip_706['dist']
print(trip_706['Inst Fuel Consumption'].sum())
trip_706.tail(200)

#trip_706.to_csv('706.csv', sep=',', encoding='utf-8') 
trip_706['Inst Fuel Consumption'].value_counts()
trip_706['Inst Fuel Rate'].value_counts()
trip_706['Vehicle Speed[km/h]'].value_counts()

inf

/usr/local/anaconda3/envs/nvfel/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/usr/local/anaconda3/envs/nvfel/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/usr/local/anaconda3/envs/nvfel/lib/python3.7/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
/usr/local/anaconda3/envs/nvfel/lib/python3.7/site-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

0.0     71
64.0    29
40.0    28
62.0    27
37.0    25
        ..
9.0      1
14.0     1
16.0     1
48.0     1
27.0     1
Name: Vehicle Speed[km/h], Length: 67, dtype: int64

In [159]:
trip_706['Inst Fuel Consumption'].sum(axis=1,dtype=np.float64)

ValueError: the 'dtype' parameter is not supported in the pandas implementation of sum()